SMD-Bioinformatics-Lund/gens

static/js/genecanvas.js
The name of this branch is incorrect... should be `better-x-ticks`
This changes the X ticks from being at fixed positions with essentially random numbers:
to use a tick interval of even powers of ten (10, 100, 1000) or "half-steps" (50, 500, 5000).
=> Better X ticks

static/js/annotation.js, static/js/interactive.js, static/js/track.js, static/js/transcript.js
Makes things appear smoother since the database fetch takes
a couple 100 ms, during which the tracks were empty creating a
flickering feeling.
=> Move clearTracks to just before redrawing them

gens.py, static/js/interactive.js
Some performance improvements for getting coverage data from backend.  
1. Use pysam for tabix queries instead of external tabix executable
2. Send plot positions from backend to frontend as integers rather than floats. Since data is sent as json, this reduces the amount of transferred data by 60-70%
=> Performace

CHANGELOG.md, gens/static/js/interactive.js
This adjusts the size and position of the "Loading..." div to avoid drawing it above UI stuff.
Lots of magic numbers, but meh...
=> Adjust position and size of the loadingDiv to avoid covering borders

CHANGELOG.md, assets/js/annotation.js, assets/js/track.js, assets/js/transcript.js, assets/js/variant.js, gens/config.py, utils/update_transcripts.py
This PR fixes issues relating to rendering of transcripts in Gens. 
1. Clone and setup a new dev environment of Gens
2. Load transcripts using the command, `./utils/update_transcripts.py --file /home/app/data/Homo_sapiens.GRCh38.101.gtf --mane /home/app/data/MANE.GRCh38.v0.92.summary.txt`
3. Navigate to, http://10.0.224.64:5003/643594?region=21:25582700-25611507
4. Navigate to, http://10.0.224.64:5003/643594?region=1:920355-961815
1. Gene names should be centered under the displayed portion of the transcript
2. Transcripts on forward and reverse strand should be indicated with different colors
3. MANE transcript should be marked with a brighter color and have MANE in its name
**Review:**
=> Fix missing gene names

CHANGELOG.md, assets/css/error.scss, assets/js/track.js, gens/api.py, gens/blueprints/gens/templates/gens.html, gens/db/db.py
This PR fixes an instance where Gens api crashed when querying for variants from a case not in Scout db. It disables an annotation track if the data could not be fetched. 
**Review:**
=> Fix missing variant api crash

CHANGELOG.md, assets/js/interactive.js
This PR makes the "loadingDiv" not show up when panning with the mouse, and instead changes the cursor to "wait".
=> Don't show 'loading...' when panning with the mouse

CHANGELOG.md, gens/blueprints/gens/templates/gens.html
This moves annotation tracks in the template to a macro. 
I am not using the macro for `interactive-container`, since it is different at almost every line...
=> Use template macros for annotation tracks

CHANGELOG.md, assets/css/gens.scss, assets/js/interactive.js, assets/js/track/annotation.js, assets/js/track/base.js, assets/js/track/base.test.js, assets/js/track/tooltip.js, assets/js/track/transcript.js, assets/js/track/utils.js, assets/js/track/utils.test.js, assets/js/track/variant.js, gens/blueprints/gens/templates/gens.html, package-lock.json, package.json
This PR re-implements tooltips
1. Setup a demo instance of Gens
2. For each step, hover mouse pointer on annotated regions.
- Navigate to: http://10.0.224.64:5003/643594?region=8:141468074-141468213&variant=84af935d282baeb23862b3c28670f9f9
- Zoom out to display region, 8:141380052-141556319
- Navigate to region, 8:143789474-143893570
- One tooltip per element should be displayed
- Tooltips should be centered on the segments of the elements that are visible
- Tooltips should contain relevant information
- For transcripts, the tooltip should display information on element features when hovering the mouse over them
**Review:**
=> Display annotation information in tooltips

CHANGELOG.md, gens/__version__.py, package.json, setup.py
- Command line interface for manageing Gens
- Commands for loading transcripts, annotations and chromosome size into database
- Include api spec, html and static files in distribution
- Display when databases last updated in /about.html
- Display current configuration /about.html
- Added landing page that show uploaded samples
- Added load sample command for loading samples into gens database
- Added index command for creating new indexes
- Added view sample command for displaying sample information
- Added pagination samples table
- Changed development status from Alpha to Stable
- Samples are loaded based on the paths given when uploading the sample
- Gens no longer uses HG38_PATH and HG37_PATH variables
- Use genome build instead of hg_type throughout the codebase and in API calls
- …
=> Release 2.0.0

CHANGELOG.md, gens/__version__.py, package.json
- Added seperate error page for when accessing a sample not in the database
- load chromosome-info stores centromere position and cyto band info
- Display viewed chromosome region in cytogenetic ideogram figure
- Can now display samples that doesnt have data on all chromosomes
=> Release notes for version 2.1.0

CHANGELOG.md, setup.cfg, setup.py
This PR updates Gens to version 2.1.1
- Updated flask and pinned connexion to v2
- Fixed annotation tracks being hidden behind other elements
- Increased contrast of region selector
- Chromosome bands are displayed properly
=> Changed Gens version 2.1.1

CHANGELOG.md, Dockerfile, gens/blueprints/gens/views.py, gens/cache.py
This PR fixes a bug that could cause the wrong to be displayed different regions were being displayed for the same case at the same time.
close #133 
1. Use example variant in production Gens, http://cmdscout2.lund.skane.se/gens/24MD00143?region=6:32002301-32016300&variant=ee7d5522e87b70eb5bf525a6fce18104&genome_build=38&case_id=24MD00143&individual_id=24MD00143
2. Try repoducing the bug by first opening the variant in the production version of Gens.
3. Then change chromosome 6 to 8 in the url just after the page has loaded
4. Verify that the chromosome number has not changed to 8 and the variant is still being displayed.
5. Open the same variant in the dev version of Gens by replacing `gens` with `gens_dev` in the URL and repeat the steps above to reproduce the bug, …
=> Fix caching to prevent displaying the wrong variant

CHANGELOG.md, gens/db/annotation.py
This PR replaces the deprecated `db.remove` with `db.delete_many`.
=> Fixed bug that prevented updating annotation tracks

CHANGELOG.md, gens/commands/index.py, gens/db/index.py
This PR fixes an issue where `gens index` did not respect a negative answer to the confirmation to reindex the database.
=> Fix declining creating indexes still starts indexing

CHANGELOG.md, gens/blueprints/gens/views.py
Gens now throws a error when trying to open a sample without providing a case id.
=> Opening a sample without a case id causes endless loading of the app

.gitignore, CHANGELOG.md, assets/js/constants.ts, assets/js/draw/graph.ts, assets/js/draw/shapes.ts, assets/js/fetch.ts, assets/js/gens.test.ts, assets/js/gens.ts, assets/js/interactive.ts, assets/js/navigation.test.ts, assets/js/navigation.ts, assets/js/overview.ts, assets/js/track/annotation.ts, assets/js/track/base.ts, assets/js/track/ideogram.ts, assets/js/track/tooltip.ts, assets/js/track/transcript.ts, assets/js/track/utils.ts, assets/js/track/variant.ts, assets/js/types.ts, gens/blueprints/gens/templates/gens.html, gulpfile.js, jest.config.js, package.json, tsconfig.json, webpack.config.cjs
=> Resolve all tsc errors

CHANGELOG.md, gens/api.py
This PR just remove some code that dont seem to do anything since the data passed to the API entrypoint is validated by connexion.
When passed invalid json
```
$ curl 'http://localhost:8080/api/get-multiple-coverages' -X POST -H 'Content-Type: application/json' --data-raw 'abc'
{
"detail": "Request body is not valid JSON",
"status": 400,
"title": "Bad Request",
"type": "about:blank"
}
```
When post incomplete request
```
$ curl 'http://localhost:8080/api/get-multiple-coverages' -X POST -H 'Content-Type: application/json' --data-raw '{"foo": "bar"}'
pydantic_core._pydantic_core.ValidationError: 12 validation errors for QueryChromosomeCoverage
```
When passed non-json data (application/x-www-form-urlencoded content type)
```
curl 'http://localhost:8080/api/get-multiple-coverages' -X POST -H …
```
=> 231 returned data without declaring it first in get multiple coverages

CHANGELOG.md, README.md, docker-compose.yml, gens/commands/load.py, gens/config.py, gens/config.toml, gens/db/db.py
This PR adds the option to configure Gens using a custom toml file that can be mounted to the container. The path to the config is specified using the `CONFIG_FILE` environment variable and should be a path inside the container and point to a location where the `worker` user have read permission.
Configs have the following priority order
1. Env variables
2. Dotfile
3. Custom toml
4. Default configuration (found in `config.toml`)
Example of using a custom config toml. Add the following to the `docker-compose.dev.yml`
```yaml
services:
gens:
environment:
- CONFIG_FILE=/home/worker/user.conf.toml
volumes:
- ./user.conf.toml:/home/worker/user.conf.toml
```
The custom toml
```toml
[oauth]
discovery_url = "http://www.oauth.toml.com"
```
For test simplicity add this at the …
=> Add option to configure Gens with toml files

assets/js/components/input_controls.ts, assets/js/components/tracks/annotation_tracks.ts, assets/js/components/tracks/multi_track.ts, assets/js/components/tracks_manager.ts, assets/js/state/api.ts, assets/js/state/parse_data.ts, assets/js/types.ts, gens/crud/annotations.py, gens/crud/samples.py, gens/load/annotations.py, gens/models/annotation.py, gens/models/genomic.py, gens/routes/annotations.py
Brings back annotations to the front end after various back-end changes.
* Various parsing fixes to allow non-perfect formatting of aed files (these files contain manual inputs and can have many different shapes and looks). We might want to consider keeping the even more permissive approach from before - just skipping entries that are not correct while emitting a warning.
* Chromosome included in annotations returned to front end.
* UI considers that the select now distinguishes track IDs and labels.
=> Annotations fixes

CHANGELOG.md, assets/js/components/tracks_manager.ts, assets/js/gens.ts, assets/js/state/api.ts, assets/js/state/parse_data.ts, gens/auth.py, gens/blueprints/gens/templates/gens.html, gens/blueprints/gens/views.py, gens/blueprints/login/views.py, gens/config.py, gens/config.toml, gens/crud/user.py, gens/routes/annotations.py
Various fixes and optimizations for running on server.
* Cache promises instead of actual data for API requests, to prevent repeated requests before the data request is completed.
* Gens API point in config file.
* Option to return MANE select only directly from API (to avoid transferring 30MB and then parsing out the needed 4MB client side).
=> Get running on server

assets/css/gens.scss, assets/js/components/input_controls.ts, assets/js/components/settings_page.ts, assets/js/components/side_menu.ts, assets/js/components/tracks/overview_track.ts, assets/js/components/util/choice_select.ts, assets/js/gens.ts, assets/js/state/api.ts, gens/blueprints/gens/templates/gens.html, gens/cli/load.py, gens/load/annotations.py
Various fixes to get annotations running on Gens dev.
Backend
* Parsing annotations allows a more liberal option to skip errors `--ignore-errors`. Currently only active for aed files. We should work through the errors and probably many of these can be fixed by our users. The current crash only was too blocking though.
* Extract the choices select component into its own web component.
* Move the annotations select into the setting side bar. In the future, more selects will be there (sample annotations, panels (?)).
Moving the annotation select into the side bar turned out to be a bit tricky due to how event targeting works with the shadow dom, and due to that Choices had not yet been adapted for this. A prototype update of the imported Choices component resolved this.
=> Deploy annotations

CHANGELOG.md, assets/css/gens.scss, assets/js/components/header_info.ts, assets/js/components/input_controls.ts, assets/js/components/settings_page.ts, assets/js/components/side_menu.ts, assets/js/components/tracks/band_track.ts, assets/js/components/tracks/base_tracks/canvas_track.ts, assets/js/components/tracks/base_tracks/data_track.ts, assets/js/components/tracks/dot_track.ts, assets/js/components/tracks/overview_track.ts, assets/js/components/tracks_manager.ts, assets/js/components/util/canvas_interaction.ts, assets/js/components/util/menu_utils.ts, assets/js/components/util/popup.ts, assets/js/constants.ts, assets/js/draw/shapes.ts, assets/js/gens.ts, assets/js/util/collections.ts, assets/js/util/utils.ts
Close #345
Adds a panel in the settings page allowing the user to control showing, hiding, moving, collapsing tracks.
For now buttons for everything. Usability could be improved ahead by drag-and-drop etc.
Also adds a track menu (yet to be made functional).
Many fixme's left. The changes were growing and seemed to me I needed to wrap something intermediary here.
=> Moving, hiding, collapsing tracks

CHANGELOG.md, assets/js/components/tracks/base_tracks/data_track.ts, assets/js/components/tracks_manager.ts, assets/js/components/util/menu_content_utils.ts, assets/js/components/util/menu_utils.ts, assets/js/draw/render_utils.ts, assets/js/draw/shapes.ts, assets/js/state/api.ts, assets/js/types.ts, assets/js/util/utils.ts
Close #344
Populating the tracks menu with some actual functionality.
Same as in the tracks panel in settings (in many cases more useful to have it here, such as when moving a track).
Also adds y-axis control for dot-charts (and with that, some y-tick logic).
=> Tracks menu

assets/js/components/tracks/band_track.ts, assets/js/components/tracks/base_tracks/canvas_track.ts, assets/js/components/tracks/base_tracks/data_track.ts, assets/js/components/tracks/dot_track.ts, assets/js/components/tracks/ideogram_track.ts, assets/js/components/tracks/multi_track.ts, assets/js/components/tracks/overview_track.ts, assets/js/components/tracks_manager.ts, assets/js/gens.ts, assets/js/types.ts
Distinguish region updates (chrom, pos), window resize and others to allow more efficient rendering.
In particular the overview plot can make sure to only rerender on resize (while updating only the marking on region updates).
=> More granular settings for render

assets/js/components/header_info.ts, assets/js/components/input_controls.ts, assets/js/components/tracks/band_track.ts, assets/js/components/tracks/base_tracks/canvas_track.ts, assets/js/components/tracks/base_tracks/data_track.ts, assets/js/components/tracks/base_tracks/interactive_tools.ts, assets/js/components/tracks/dot_track.ts, assets/js/components/tracks/ideogram_track.ts, assets/js/components/tracks/overview_track.ts, assets/js/components/tracks_manager.ts, assets/js/components/tracks_manager/tracks_manager.ts, assets/js/components/tracks_manager/utils.ts, assets/js/components/util/choice_select.ts, assets/js/gens.ts, assets/js/movements/dragging.ts, assets/js/movements/marker.ts, assets/js/state/api.ts, assets/js/state/gens_session.ts, assets/js/state/parse_data.ts, assets/js/state/session.ts, assets/js/util/navigation.ts, assets/js/util/utils.ts
The tracks manager class was gradually growing beyond control. This is an attempt to tame it 🪴 
Expands the session class, by among other moving the current view state (i.e. chromosome, start, end) to it instead of the input controls in the top bar.
Also adds a Scout URL case link to the top bar.
It is kind of a good PR to look at to see whether you agree / disagree with the currently preferred TS style in Gens.
=> Refactor tracks manager

assets/js/components/header_info.ts, assets/js/components/tracks/base_tracks/data_track.ts, assets/js/components/tracks_manager/tracks_manager.ts, assets/js/constants.ts, assets/js/draw/render_utils.ts, assets/js/gens.ts, assets/js/types.ts, gens/__version__.py, gens/blueprints/gens/templates/gens.html, package.json
* Y axis now goes from low to high
* More compact top bar
* Display Gens version
* Remove the samples (anyway shown in the tracks)
=> Quick post-meeting fixes

assets/js/components/tracks/band_track.ts, assets/js/components/tracks/base_tracks/data_track.ts, assets/js/components/tracks/dot_track.ts, assets/js/components/tracks/overview_track.ts, assets/js/components/tracks_manager/track_view.ts, assets/js/components/tracks_manager/utils.ts, assets/js/constants.ts, assets/js/movements/marker.ts, assets/js/state/api.ts
* Overview chart is higher to match old Gens
* Y axis / tick lines for overview charts
* Zoom level "c" is cached
* Marker z level is set between the tracks container and the sidebar
* Always show render on loading for dot and band tracks (previously it showed a frozen picture of the previous state)
=> Fixes for overview chart, and various cleanup

assets/js/components/tracks/base_tracks/canvas_track.ts, assets/js/components/tracks/overview_track.ts, assets/js/components/tracks_manager/track_view.ts, assets/js/components/tracks_manager/tracks_manager.ts, assets/js/components/tracks_manager/utils.ts, assets/js/gens.ts, assets/js/state/api.ts, assets/js/state/parse_data.ts
It turned out Scout uses the "document_id" ID for referring to variant pages rather than the "variant_id".
=> Fix incorrect variant links

assets/js/home/sample_table.ts, gens/blueprints/home/templates/home.html
Removes div which unbeknownst stuck all the sample info from 20000 samples into a single div. This in turned ~30 seconds freeze on the samples page.
Seems to be behaving better now.
=> Remove massive data div

assets/js/components/input_controls.ts, assets/js/state/api.ts, gens/routes/annotations.py
Previously they used the same end point, which led to the specific entry requests ending up in the track endpoint instead.
=> Specific end points for full annotation track info and specific annotation entry

assets/js/components/tracks_manager/chromosome_view.ts, assets/js/components/tracks_manager/track_view.ts, assets/js/components/tracks_manager/utils.ts
Close #432
Previously in the chromosome view, the data adapted to the chromosome size, but the sample annotation did not.
=> Adjust x-range for sample annotation track in chromosome view

assets/js/constants.ts, assets/js/util/utils.ts, gens/cli/load.py, gens/cli/update.py, gens/models/sample.py
Previously, only specific sample types were allowed.
This inevitably caused issues with types not included among these.
Better to allow any type, and let the user specify a "main type" through their configuration (or default to proband / tumor).
=> Don't block on specific sample types

frontend/js/components/input_controls.ts, frontend/js/constants.ts, frontend/js/util/utils.ts
Previously hard to understand that you ended up exactly matching the edges.
Now a slight padding is added to the range when searching for a symbol.
Example RNU4-2 search
SMN2 search
Close #493
=> Visual end pad when searching for a gene or annotation
