static/js/interactive.js, static/js/overview.js, templates/gens.html
=> Add a marker which shows the interactive region in the overview

CHANGELOG.md, gens/api.py, gens/app.py, gens/graph.py, gens/io.py, gens/static/js/overview.js
This adds the ability to load BAF/cov data for the overview plot from a separate JSON file, which significantly improves the initial load time.
Also add response data compression, which further speeds things up!
=> Json overview

CHANGELOG.md, README.md, gens/api.py, gens/app.py, gens/graph.py, gens/io.py, gens/static/js/interactive.js, gens/static/js/overview.js
=> Firefox support

.github/workflows/tests.yml, CHANGELOG.md, README.md, tests/test_io.py
This PR adds unit tests using pytest as well as sets up a gitworkflow that automatically tests PRs. The current test included are very basic and are intended as a starting point to be expanded upon.
**Review:**
=> Create automated tests

CHANGELOG.md, assets/js/overview.js, gens/blueprints/gens/views.py
This PR changes the default chromosomal region to display from 1:100000-200000 to the entire chromosome 1.
**Review:**
=> Changed default chromosome region to display

CHANGELOG.md, assets/css/gens.scss, assets/js/annotation.js, assets/js/track.js, assets/js/transcript.js, assets/js/variant.js, gens/blueprints/gens/templates/gens.html
This PR adds labels to the annotation tracks
View regions 
1. http://10.0.224.64:5003/643594?region=8:141468087-141471000&variant=84af935d282baeb23862b3c28670f9f9
2. http://10.0.224.64:5003/643594?region=8:141468087-141471000&variant=84af935d282baeb23862b3c28670f9f9
3. http://10.0.224.64:5003/643594?region=8:141468087-141471000&variant=84af935d282baeb23862b3c28670f9f9
For each region, try zooming out and in so the different tracks disappear and reappear.
Ensure the annotation track labels are being displayed properly and does not overlap with one another.
**Review:**
=> Added labels to annotation tracks

CHANGELOG.md, gens/__version__.py, package.json
=> Release notes version 1.2.0

CHANGELOG.md, gens/__version__.py, package.json
- Reinstated tooltips to display additional information on genetic elements
- Use popper for positioning tooltips
**Review:**
=> Release notes version 1.2.1

CHANGELOG.md, Dockerfile, gens/app.py, gens/blueprints/gens/views.py, gens/commands/load.py, gens/config.py, gens/constants.py, gens/utils.py, setup.py
This PR fix the hg_type issue which caused Gens to crash. Gens should now be able load samples.
**Review:**
=> Genome build bugfix

CHANGELOG.md, assets/css/home.scss, gens/api.py, gens/blueprints/home/templates/home.html, gens/blueprints/home/views.py, gens/commands/load.py, gens/commands/view.py, gens/db/__init__.py, gens/db/samples.py, gens/load/__init__.py
This pr adds pagination to sample page
**Review:**
=> Sample page pageination

CHANGELOG.md, gens/app.py, gens/db/__init__.py, gens/db/samples.py, gens/errors.py, gens/templates/sample_not_found.html
**Review:**
- [x ] code approved by Markus
=> Display sample not found when sample not in db

CHANGELOG.md, gens/app.py, gens/db/samples.py, gens/io.py
- Missing tbi files results in 404 error
- Fixed sort order of samples table
- Do not thow warnings when using default config
**Review:**
=> Fix various minor bugs

CHANGELOG.md, assets/js/overview.js, assets/js/track/variant.js, gens/graph.py
This PR the issue with displaying samples with one or more chromosomes without coverage information
**Review:**
=> Allow for chrom wo cov

CHANGELOG.md, gens/__version__.py, package.json
This PR release a new version of Gens
- Changed cached method from simple to file system as it would be thread safe
- Fixed cache issue that could result in chromosome information not being updated
- Fixed max arg error when searching for some genes
=> Release 2.1.2

CHANGELOG.md, assets/css/gens.scss, assets/css/navbar.scss
The PR corrects the path to the logotype it is now being displayed.
=> Fixed logotype path in the navbar

CHANGELOG.md, Dockerfile.dev, docker-compose.dev.yml, docker-compose.yml, setup.py
This PR improves the development setup by adding a new Dockerfile and compose file for development.
- `Dockerfile` is for deployment
- `Dockerfile.dev` is for development
- `docker-compose.yml` is for setting up a deployment like instance.
- `docker-compose.dev.yml` overrides things in the `docker-compose.yml` to setup a development instance.
- Setup dev instance with `docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d`
- Setup deployment-like instance with `docker compose up -d`
=> Improved development setup

CHANGELOG.md, gens/commands/load.py, gens/load/annotations.py
This PR fixes issues in the bed parser function that prevented annotations in bed format from being loaded into Gens.
=> Fixed parsing and loading of annotations in bed format

CHANGELOG.md, gens/db/index.py
=> Update gens index to account for case_id

CHANGELOG.md, gens/db/index.py
=> Remove unique case ID constraint

CHANGELOG.md, utils/load_hg002_from_dump.sh
=> Add quick load script

gens/api.py, gens/graph.py
OR
Close #247
Also ignoring some type issues for now, such that we have a clean typing check for future PRs.
We should get back to those FIXME's soon.
**Review:**
=> Fix errors caused by type rewrite

gens/commands/delete.py, gens/commands/load.py, gens/commands/util.py
Fixes an issue introduced by previous PR.
**Review:**
=> Use the custom choice for genome build

assets/js/components/genstracks.ts, assets/js/components/tracks/band_track.ts, assets/js/components/tracks/canvas_track.ts, assets/js/components/tracks/render_utils.ts, assets/js/gens.ts, assets/js/state/gens_api.ts, assets/js/state/requests.ts, assets/js/track/utils.ts, assets/js/types.ts
=> Variants and moving API data parsing

assets/js/components/genstracks.ts, assets/js/components/tracks/band_track.ts, assets/js/components/tracks/canvas_track.ts, assets/js/track/annotation.ts
=> Week cleanup

assets/js/components/genstracks.ts, assets/js/components/tracks/band_track.ts, assets/js/components/tracks/canvas_track.ts, assets/js/components/tracks/render_utils.ts, assets/js/components/tracks/tooltip_utils.ts, assets/js/track/utils.ts, assets/js/types.ts, assets/js/util/constants.ts
=> Expanding tracks and lanes working

assets/css/gens.scss, assets/js/components/input_controls.ts, assets/js/components/top_bar.ts, assets/js/components/tracks_manager.ts, assets/js/draw/shapes.ts, assets/js/gens.ts, gens/blueprints/gens/templates/gens.html
Fixed top bar, and input controls moved to the top bar.
=> Styling updates

assets/css/gens.scss
=> CSS cleanup

assets/css/gens.scss, assets/js/components/tracks/annotation_tracks.ts, assets/js/components/tracks/band_track.ts, assets/js/components/tracks/canvas_track.ts, assets/js/components/tracks/dot_track.ts, assets/js/components/tracks/ideogram_track.ts, assets/js/components/tracks/overview_track.ts, assets/js/components/tracks_manager.ts, assets/js/components/util/popup.ts, assets/js/components/util/shadowbase.ts, assets/js/constants.ts, assets/js/draw/render_utils.ts, assets/js/draw/shapes.ts, assets/js/gens.ts, assets/js/state/parse_data.ts, assets/js/types.ts, assets/js/util/popup_utils.ts, assets/js/util/utils.ts, package-lock.json, package.json
Tracks are also refactored to separate out the setup (constructor) from rendering steps (initialize and render).
=> Variant linkback, popups and refactoring tracks

gens/cli/load.py, gens/crud/search.py, gens/crud/transcripts.py, gens/db/index.py, gens/load/annotations.py, gens/models/annotation.py, gens/models/search.py, gens/routes/base.py
This PR adds a API entrypoint for making text searches against the anotation and transcript collections which returns a list of suggestions.
=> Search suggestions

assets/js/components/input_controls.ts, assets/js/components/tracks/band_track.ts, assets/js/components/tracks/canvas_track.ts, assets/js/components/tracks/dot_track.ts, assets/js/components/tracks/ideogram_track.ts, assets/js/constants.ts, assets/js/draw/ideogram.ts, assets/js/draw/render_utils.ts, assets/js/types.ts
Resolved issues:
* Re-renders does not leave lingering edges from previous renders
* Hovers shows the correct chromosome segments
* Paddings correctly rendered
Beyond that, the code has been refactored and simplified. Notably:
* Using a scale to keep track of x-position, dropping keeping track of paddings throughout
* Use CanvasTrack built in hover logic, dropping the custom popper logic
* Refactoring and documenting functions
=> Resolve chromosome infogram issues

assets/js/components/input_controls.ts, assets/js/components/tracks/band_track.ts, assets/js/components/tracks/canvas_track.ts, assets/js/components/tracks/dot_track.ts, assets/js/components/tracks/ideogram_track.ts, assets/js/components/tracks/overview_track.ts, assets/js/components/tracks_manager.ts, assets/js/gens.ts, assets/js/state/api.ts, assets/js/state/parse_data.ts, assets/js/types.ts, gens/io.py, gens/routes/sample.py
Fixes:
* Front-end considers zoom when making requests to the backend
* Back-end supports taking a zoom level
* Region controller in input controls is not directly linked to the input field anymore
* Fix issue where longer annotations surrounding the current x range did not display
* Fix issue where annotation tracks were recreated on each render
=> Dynamic zoom

assets/js/components/tracks/band_track.ts, assets/js/components/tracks/canvas_track.ts, assets/js/components/tracks/dot_track.ts, assets/js/components/util/popup.ts, assets/js/state/api.ts, assets/js/util/popup_utils.ts
Some UI fixes
* Popup is draggable
* Show "loading" for tracks when data is refreshed
* Don't show hover element until track is rendered
=> Draggable popup

assets/js/components/header_info.ts, assets/js/components/side_menu.ts, assets/js/components/tracks_manager.ts, assets/js/components/util/menu_utils.ts, assets/js/constants.ts, assets/js/gens.ts, assets/js/types.ts, gens/blueprints/gens/templates/gens.html
* Sidebar styling
* Making URLs clickable
* Show samples and case in header bar
=> Sidebar styling and header info

assets/js/components/tracks/overview_track.ts, assets/js/components/tracks_manager.ts, assets/js/constants.ts
=> Chromosome numbers

CHANGELOG.md, assets/js/components/tracks/band_track.ts, assets/js/components/tracks/base_tracks/canvas_track.ts, assets/js/components/tracks/base_tracks/data_track.ts, assets/js/components/tracks/dot_track.ts, assets/js/components/tracks_manager.ts, assets/js/gens.ts, assets/js/state/api.ts, assets/js/state/parse_data.ts, assets/js/types.ts, gens/blueprints/gens/templates/gens.html, gens/blueprints/gens/views.py, gens/blueprints/home/templates/home.html, gens/blueprints/home/views.py, gens/crud/samples.py
Close #116 
Case oriented sample page
If opening the case, it now displays multiple coverage tracks
=> Display coverage for multiple samples

gens/constants.py, gens/load/transcripts.py, gens/routes/annotations.py
To address PR comment https://github.com/SMD-Bioinformatics-Lund/gens/pull/326/files/f6cd67bf573dcfe00aa4d3b3b1fabab59e0b4b92#r2071238108
I made a new module for Python constants (we have a similar in the typescript folder). There might be other constants which could migrate there as well eventually.
As a consequence of fixing this, it lead me to realize that the MANE plus are considered in other parts of the code. I.e. this refactor resolved an untriggered bug. Nice 👌 One more + for using constants.
=> Constants for MANE

CHANGELOG.md, assets/js/components/tracks/base_tracks/data_track.ts, assets/js/components/tracks_manager.ts, assets/js/gens.ts, package-lock.json, package.json
Adds a small external dependency. First I attempted doing this manually, which was not as smooth. I think for this impact it is worth using the Sortable library. Hopefully I won't be cursed in five years for this decision 🙄
=> Drag and drop

assets/js/components/side_menu/side_menu.ts, assets/js/components/tracks/band_track.ts, assets/js/components/tracks/base_tracks/data_track.ts, assets/js/components/tracks/base_tracks/interactive_tools.ts, assets/js/components/tracks_manager/tracks_manager.ts, assets/js/components/tracks_manager/utils.ts, assets/js/components/util/canvas_interaction.ts, assets/js/components/util/menu_utils.ts, assets/js/gens.ts
* Prevent band rendering over y-axis area
* Prevent range highlights over y-axis area
* Fix event listener bugs when moving tracks led to loss of hover marker and track title clickability
* Restore arrow navigation shortcuts
=> Cleanup fixes

CHANGELOG.md, assets/js/components/side_menu/settings_page.ts, assets/js/components/tracks/band_track.ts, assets/js/components/tracks/base_tracks/canvas_track.ts, assets/js/components/tracks/base_tracks/data_track.ts, assets/js/components/tracks/dot_track.ts, assets/js/components/tracks/ideogram_track.ts, assets/js/components/tracks/overview_track.ts, assets/js/components/tracks_manager/tracks_manager.ts, assets/js/components/tracks_manager/utils.ts, assets/js/constants.ts, assets/js/gens.ts, assets/js/state/gens_session.ts
Adds the option to customize collapsed and expanded heights of tracks.
=> Custom track heights

CHANGELOG.md, gens/cli/load.py, gens/load/annotations.py
Allow multi-line comments and gracefully continue with warnings / errors on multiple conditions.
=> Further parsing aed files

assets/js/components/tracks/band_track.ts, assets/js/components/tracks/base_tracks/data_track.ts, assets/js/components/tracks/base_tracks/interactive_tools.ts, assets/js/components/tracks/dot_track.ts, assets/js/components/tracks/overview_track.ts, assets/js/components/tracks_manager/chromosome_view.ts, assets/js/components/tracks_manager/track_view.ts, assets/js/components/tracks_manager/tracks_manager.ts, assets/js/components/util/choice_select.ts, assets/js/gens.ts, assets/js/movements/marker.ts, gens/blueprints/home/templates/home.html, gens/blueprints/home/views.py, gens/crud/samples.py
Working through a number of smaller issues before dev deployment.
=> Various pre-dev-deployment fixes

assets/js/components/tracks_manager/track_view.ts, assets/js/components/tracks_manager/utils.ts
Fixes a small bug where chromosome 1 always was used to retrieve the genes.
=> Fix such that correct chromosome is used for genes

assets/js/components/tracks/base_tracks/canvas_track.ts, assets/js/components/tracks/base_tracks/data_track.ts, assets/js/components/tracks/dot_track.ts, assets/js/components/tracks/position_track.ts, assets/js/components/tracks_manager/track_view.ts, assets/js/components/tracks_manager/utils.ts, assets/js/constants.ts, assets/js/types.ts, assets/js/util/utils.ts
=> Position track

CHANGELOG.md, assets/js/home/gens_home.ts, assets/js/home/sample_table.ts, gens/cli/load.py, gens/crud/transcripts.py, gens/load/transcripts.py, gens/models/annotation.py
Some backend changes was needed to get transcripts loaded after adding the Pydantic models.
I took the chance to also remove the now unused height order property from the db transcripts.
=> Tighten up transcript loading

CHANGELOG.md, assets/js/components/input_controls.ts, assets/js/components/tracks/band_track.ts, assets/js/components/tracks/base_tracks/canvas_track.ts, assets/js/components/tracks/position_track.ts, assets/js/components/tracks_manager/chromosome_view.ts, assets/js/gens.ts, assets/js/state/api.ts, assets/js/state/parse_data.ts, assets/js/util/fetch.ts, gens/crud/samples.py, gens/crud/search.py, gens/io.py, gens/models/sample.py, gens/routes/base.py, gens/routes/sample.py, package.json
* If no overview file is supplied, the overview chart is generated from "o" zoom level data
* Search within annotations works (also on partial string matches)
* Search for transcript goes to the position of the MANE transcript
* Fix various ESLint issues
Close #389
Close #396
Close #391
=> Search fixes and overview track fix

CHANGELOG.md, assets/js/components/side_menu/side_menu.ts, assets/js/components/tracks_manager/track_view.ts, assets/js/components/tracks_manager/utils.ts, assets/js/constants.ts, assets/js/gens.ts, assets/js/state/gens_session.ts, assets/js/util/utils.ts, gens/blueprints/gens/templates/gens.html, gens/blueprints/gens/views.py, gens/blueprints/home/views.py, gens/cli/load.py, gens/cli/update.py, gens/config.py, gens/config.toml
* Close #437
* Close #427
* Adjustable context menu width (more narrow for band context menues, wider for settings and meta data)
=> Gens fixes

gens/cli/update.py, gens/crud/samples.py, tests/cli/test_sample.py
=> Consider genome build in update command

frontend/js/types.ts, gens/blueprints/home/views.py, gens/cli/load.py, gens/cli/update.py, gens/crud/samples.py, gens/models/sample.py, tests/cli/test_sample.py
Adding it needed more intrusive changes than first anticipated.
Backing away from it for now. Let's add it properly again ahead.
=> Remove institute support from code again for now

frontend/js/components/tracks/base_tracks/data_track.ts, frontend/js/constants.ts
=> Lighter coloring

.github/workflows/ci.yml, CHANGELOG.md
Not something we are looking at, and flaked out in a separate PR. So I thought let's just remove it.
=> Skip coveralls CI

.github/workflows/ci.yml, CHANGELOG.md, gens/blueprints/gens/templates/gens.html
=> Fix string region for direct variant location through url

CHANGELOG.md, frontend/js/components/util/menu_utils.ts
=> ClinVar IDs -> links in annotations
